[package]
name = "verifine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cranelift-isle = { version = "*", path = "../isle/", features = ["fancy-errors", "logging"] }
env_logger = { workspace = true }
clap = { workspace = true, features = ['default'] }
